apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: cbt-client
  name: cbt-client
spec:
  selector:
    matchLabels:
      app: cbt-client
  template:
    metadata:
      labels:
        app: cbt-client
    spec:
      containers:
      - command:
        - sh
        - -c
        - tail -f /dev/null
        image: bitnami/kubectl:latest
        imagePullPolicy: Always
        name: ubuntu
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
      restartPolicy: Always
      serviceAccountName: cbt-client
