apiVersion: v1
kind: ServiceAccount
metadata:
  name: cbt-client
  namespace: cbt-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cbt-client-role
  namespace: cbt-client
rules:
  - apiGroups:
      - 'cbt.storage.k8s.io'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cbt-client-rolebinding
  namespace: cbt-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cbt-client-role
subjects:
  - kind: ServiceAccount
    namespace: cbt-client
    name: cbt-client
