---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbt-datapath-apiserver
  namespace: cbt-svc
  labels:
    api: cbt-datapath
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: cbt-datapath
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: cbt-datapath
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: prasadg193/cbt-datapath:latest
        volumeMounts:
        - mountPath: /apiserver.local.config/certificates
          name: apiserver-certs
          readOnly: true
        - mountPath: /apiserver.local.config/certificates/ca
          name: apiserver-ca-cert
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        env:
        - name: CBT_SERVER_CA_BUNDLE
          value: /apiserver.local.config/certificates/ca/ca.crt
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: sample-driver
        image: prasadg193/sample-driver:latest
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        env:
        - name: CBT_SERVER_CERT
          value: "/apiserver.local.config/certificates/tls.crt"
        - name: CBT_SERVER_KEY
          value: "/apiserver.local.config/certificates/tls.key"
        - name: NUMBER_OF_BLOCKS
          value: "5"
      volumes:
      - name: apiserver-certs
        secret:
          secretName: cbt-datapath
      - name: apiserver-ca-cert
        secret:
          secretName: cbt-datapath-ca-cert
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: cbt-datapath
  namespace: cbt-svc
  labels:
    api: cbt-datapath
    apiserver: "true"
data:
  tls.crt: 
  tls.key: 
---
apiVersion: v1
kind: Service
metadata:
  name: cbt-datapath
  namespace: cbt-svc
  labels:
    api: cbt-datapath
    apiserver: "true"
spec:
  ports:
  - name: aggapi
    port: 443
    protocol: TCP
    targetPort: 443
  - name: cbt
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    api: cbt-datapath
    apiserver: "true"
