
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cbt.storage.k8s.io
  labels:
    api: cbt-datapath
    apiserver: "true"
spec:
  version: v1alpha1
  group: cbt.storage.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: cbt-datapath
    namespace: cbt-svc
  versionPriority: 10
  caBundle: 
---
